id: P0AA296A9
initial_creation_type: input
source_metadata:
  title: Götsangpa Gönpo Dorje
  language: en
  description: 'Texts by and about Götsangpa Gönpo Dorje (rgod tshang pa mgon po rdo
    rje, 1189–1258):'
  volume:
    c2a0f3354fc94bab95755dd9b2d3c6e4:
      title: The Fourfold 'Manam' Refuge
      parent: Prayers
    138d0b0179c0481ab71c1676e59b0e3c:
      title: 'The Tamboura of Devotion: A Prayer to Götsang Gönpo Dorje'
      parent: Prayers
created_at: '2022-02-28T23:25:47.627461'
last_modified_at: '2022-02-28T23:25:47.627467'
